const number1 = 2;
const number2 = 4;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 100;
const payment = 20;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const tests = 90;
const assignments = 80;
const final = 100;
const grade = ((tests + assignments + final) / 3);
console.log(grade);
console.log(typeof grade);
const firstName = 'James ';
const lastName = 'Aguirre';
const fullName = `${firstName}${lastName}`;
console.log(fullName);
console.log(typeof fullName);
const pH = 6;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 600;
const isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname = fullName + ' is the GOAT';
console.log(nickname);
console.log(typeof nickname);
